# This extends the _local file, run with:
#   `docker-compose -f docker-compose_local.yml -f docker-compose_local_reload.yml up`
version: '3.7'
services:
  api:
    image: pttbackend:devel_shell
    build:
      context: .
      dockerfile: Dockerfile
      target: devel_shell
    command: ["-c", "source /root/.profile && poetry install && uvicorn --host 0.0.0.0 --port 8000 --log-level debug pttbackend.api:APP --reload"]
    volumes:
      - "./:/app"
