"""Initial schema and tables

Revision ID: a424058071b6
Revises:
Create Date: 2023-03-03 13:17:43.036877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a424058071b6"  # pragma: allowlist secret
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create schema takbackend")

    op.create_table(
        "takinstances",
        sa.Column("ownerid", sa.Unicode(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("grouping", sa.Unicode(), nullable=False),
        sa.Column("tfcompleted", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tfinputs", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("tfoutputs", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("pk", postgresql.UUID(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("pk"),
        schema="takbackend",
    )
    op.create_index(
        op.f("ix_takbackend_takinstances_color"), "takinstances", ["color"], unique=False, schema="takbackend"
    )
    op.create_index(
        op.f("ix_takbackend_takinstances_grouping"), "takinstances", ["grouping"], unique=False, schema="takbackend"
    )
    op.create_index(
        op.f("ix_takbackend_takinstances_ownerid"), "takinstances", ["ownerid"], unique=False, schema="takbackend"
    )
    op.drop_table("alembic_version")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alembic_version",
        sa.Column("version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("version_num", name="alembic_version_pkc"),
    )
    op.drop_index(op.f("ix_takbackend_takinstances_ownerid"), table_name="takinstances", schema="takbackend")
    op.drop_index(op.f("ix_takbackend_takinstances_grouping"), table_name="takinstances", schema="takbackend")
    op.drop_index(op.f("ix_takbackend_takinstances_color"), table_name="takinstances", schema="takbackend")
    op.drop_table("takinstances", schema="takbackend")

    op.execute("drop schema takbackend")
    # ### end Alembic commands ###
